### ISSUE TITLE
Wrong database table when click on "Stripe Checkout" in CraftCMS 3 Admin

### ISSUE THREAD

**Issue by landandwater** [lukeyouell/craft-stripecheckout#1]
When I click on Stripe Checkout in my Craft 3 admin, I get this error. It's looking for the wrong table name. I checked the database, and the transactions are in it, but the table name it should be looking for is 'uislthd_crafty.craft_stripecheckout_charges', and not 'uislthd_crafty.stripecheckout_charges'

Internal Server Error
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uislthd_crafty.stripecheckout_charges' doesn't exist The SQL being executed was: SELECT * FROM stripecheckout_charges ORDER BY dateCreated DESC

**Comment by lukeyouell** [comment]
@landandwater looks like I may have missed something here, but I'm unable to replicate your error.

Please can you replace:
 
`stripecheckout_charges` 

on lines 27 & 32 of `services/RecordService.php` with:

`{{%stripecheckout_charges}}`

and see if that does the trick?

**Comment by landandwater** [comment]
@lukeyouell Works, Thank you!

**Comment by lukeyouell** [comment]
@landandwater good to hear! I'll have the fix released at some point tomorrow.
