### ISSUE TITLE
Use custom form

### ISSUE THREAD

**Issue by hassanmah** [lukeyouell/craft-stripecheckout#10]
Hi,

How do I go about using a custom form with the following fields:

- Email address
- Card number
- Expiry date
- CVC
- Zip code

Thanks

**Comment by lukeyouell** [comment]
@hassanmah this plugin is only intended to support the standard Stripe Checkout setup. 

So unfortunately that functionality isn't available with this particular plugin.

**Comment by hassanmah** [comment]
Is it possible to get the stripeid back upon successful payment?

**Comment by lukeyouell** [comment]
@hassanmah https://github.com/lukeyouell/craft-stripecheckout/blob/v2/docs/creating-charges.md#redirecting
