### ISSUE TITLE
Live secret key gets overriden bij live publishable key

### ISSUE THREAD

**Issue by GillisWerrebrouck** [lukeyouell/craft-stripecheckout#11]
On the credentials page of the stripe plugin in craft 3, the live secret key field is always the same as the publishable key field. It doesn't matter what is filled in in the live sk field, it is always the same as the live pk field.
I reinstalled the plugin, filled out all the credential fields correctly but this didn't fix it according to what was visible on the credential page. Although the value is probably in the database because a transaction was correctly executed after this reinstallation.

**Comment by lukeyouell** [comment]
@GillisWerrebrouck fixed & released!
