### ISSUE TITLE
Custom popup template?

### ISSUE THREAD

**Issue by rachelrine** [lukeyouell/craft-stripecheckout#14]
Just wondering if it's possible to customize the popup window that collects the credit card info, or potentially incorporate those fields into a larger checkout form.

**Comment by lukeyouell** [comment]
@rachelrine I'm afraid not, unless you override Stripe somehow. The plugin is only intended to work with Stripe Checkout, it sounds like youre after Stripe.js.

https://stripe.com/docs/stripe-js
