### ISSUE TITLE
Using a custom stripe button

### ISSUE THREAD

**Issue by jeromecoupe** [lukeyouell/craft-stripecheckout#15]
Hey there. Perfectly happy with the way the plugin works with Stripe Checkout but having this blue button is not an option on this project. Is there a relatively easy way to use the custom checkout JS to have a custom button ?

I cannot for the life of me figure out how to pass everything your plugin needs to it with the custom JS provided by Stripe

This is my first simple e-commerce project so forgive me if I am a bit of a noob.

**Comment by lukeyouell** [comment]
I'm afraid not as the button is rendered by Stripe, so you'll have to manually override the Stripe's CSS.
