### ISSUE TITLE
Unable to verify your data submission.

### ISSUE THREAD

**Issue by j-greig** [lukeyouell/craft-stripecheckout#2]
I got this error message after completing a test payment.
Guessing it's because I don't have HTTPS enabled on my staging server, but what else could it be?

Nice plugin btw :)

**Comment by lukeyouell** [comment]
@j-greig Like you said I think it's to do with you not using HTTPS, as per [Stripe docs](https://stripe.com/docs/api#authentication):

```
All API requests must be made over HTTPS. Calls made over plain HTTP will fail.
```

Let me know if this error persists after switching to HTTPS.

**Comment by lukeyouell** [comment]
They go into a bit more detail [here](https://stripe.com/docs/security#tls):

```
If need be, you can test your integration without using HTTPS, and enable it once you’re ready to accept live charges. However, all interactions between your server and Stripe must use TLS 1.2
```

**Comment by cole007** [comment]
I had the same issue - turns out needed to add `{{ csrfInput() }}` to the form!
