### ISSUE TITLE
Stripe Connect

### ISSUE THREAD

**Issue by samhibberd** [lukeyouell/craft-stripecheckout#4]
@lukeyouell would it be easy enough to include additional options in the `\Stripe\Charge::create()` request, we are looking to add support for Stripe's connected accounts and would just need to pass the account id and optional application fee:

```
$charge = \Stripe\Charge::create(array(
  "amount" => 1000,
  "currency" => "usd",
  "source" => "tok_visa",
  "application_fee" => 123,
), array("stripe_account" => "{CONNECTED_STRIPE_ACCOUNT_ID}"));
```

Was about to start work on a plugin to handle all this but it looks like you have most things covered here :)

Thanks

**Comment by lukeyouell** [comment]
@samhibberd this plugin is due for an update so I'll leave this issue open for when I get around to it, thanks!

**Comment by lukeyouell** [comment]
Closed via https://github.com/lukeyouell/craft-stripecheckout/commit/05e7d0c3d5443d88be2a584c6f59269ef6527f2f
